[package]
name = "zones"
version = "0.1.0"
authors = ["picania <mangustspam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10.7", features =["blocking"]}

[[bin]]
name = "get_zones"
path = "src/get_zones.rs"
